### ISSUE TITLE
The demo does not load

### ISSUE THREAD

**Issue by assman** [ahmedbeheiry/ngx-shimmer-loading#1]

**Comment by ahmedbeheiry** [comment]
Hey,
Actually it does load. Could you please try again and tell me? 
here it is >> [Demo Link](https://ngx-shimmer-loading.stackblitz.io)

**Comment by assman** [comment]
Doesn't seem to load. I can send you a video, but its not possible to attach a video to github issues

**Comment by ahmedbeheiry** [comment]
please, try again and let me know if it doesn't work.
[Demo Link](https://ahmedbeheiry.github.io/ngx-shimmer-loading/)

**Comment by assman** [comment]
Works perfectly now. Thank you
