### ISSUE TITLE
How to remove the Shimmer effect and display the content?

### ISSUE THREAD

**Issue by taksumaki** [ahmedbeheiry/ngx-shimmer-loading#2]
I want to use this add-on but I would like that I also had the option of being able to pass a boolean and that if that boolean is false, show the content, without needing to be hiding the HTML block of the shimmer and rendering another with the content.

**Comment by ahmedbeheiry** [comment]
The idea of shimmer-loading is to show a loading effect till your content is ready to be shown.. So you switch between them ( shimmer-loading and your content when ready ) using NgIf or any other technique.
