### ISSUE TITLE
Change shimmer color

### ISSUE THREAD

**Issue by daniyalawan** [ahmedbeheiry/ngx-shimmer-loading#4]
How can we customize the shimmer color?

**Comment by ahmedbeheiry** [comment]
We made an update to ngx-shimmer-loading to make it easier to style it.
Please, install latest version ( v0.0.5 ) using the install command:
`npm i --save ngx-shimmer-loading`
then, check [custom styles](https://github.com/ahmedbeheiry/ngx-shimmer-loading#custom-styles) section here.
