### ISSUE TITLE
With width applied in pixels the responsiveness losses. How to fix this?

### ISSUE THREAD

**Issue by samiullahfx** [ahmedbeheiry/ngx-shimmer-loading#5]
Hi,

I have tried adding the this shimmer effect but the issue with it is if i apply this with pixels as units for width and height then it losses its responsiveness. The div's or the boxes which are bootstrap classes they are losing their responsiveness. How to fix this issue? Any suggestions?

Eg:

<ngx-shimmer-loading *ngIf="!dataSource" [shape]="'rect'" [height]="'49px'" [width]="'1260px'" [borderRadius]="'0'"></ngx-shimmer-loading>

Thanks.

**Comment by ahmedbeheiry** [comment]
Hello,
I suppose when you apply width with pixels to any element ( whether it's an ngx-shimmer-loading or not ) you'd lose responsiveness which is something related to css. So, if you have to use width with pixels and you want it to be responsive you should consider wrapping ngx-shimmer-loading element with a container with width in pixels and using media query change that container's width. Give it a try and let me know if you have an issue related to ngx-shimmer-loading.
Thanks.
